In [1]:
import time
import torch
from torch.utils.data import TensorDataset, DataLoader

import numpy as np

import sys
sys.path.append("../..") 
import kinematics.allegro_hand as allegro
import tools.rotations as rot

%load_ext autoreload
%autoreload 2

In [11]:
x = np.linspace(-1,1,11)
y = np.concatenate([np.ones(7) * (-1), np.ones(4) * 0.5])

x = torch.Tensor(x)
y = torch.Tensor(y)

In [12]:
print(x)
print(y)

tensor([-1.0000, -0.8000, -0.6000, -0.4000, -0.2000,  0.0000,  0.2000,  0.4000,
         0.6000,  0.8000,  1.0000])
tensor([-1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000, -1.0000,  0.5000,
         0.5000,  0.5000,  0.5000])


In [14]:
torch.logical_and(x <=0, y<=0)

tensor([ True,  True,  True,  True,  True,  True, False, False, False, False,
        False])

In [15]:
cond1 = torch.logical_and(x <=0, y<=0)
cond2 = torch.logical_and(x > 0.42, y > 0.42)

loss = torch.where(torch.logical_or(cond1, cond2) ,
            torch.zeros(1),
            (x - y)**2)

In [16]:
cond3 = torch.logical_and( x > 0, y <=0)

loss_new = torch.where(cond3 ,
            10 * loss,
            loss)


In [20]:
cond3

tensor([False, False, False, False, False, False,  True, False, False, False,
        False])

In [17]:
loss

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 1.4400, 0.0100, 0.0000,
        0.0000, 0.0000])

In [18]:
loss_new

tensor([0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        1.4400e+01, 1.0000e-02, 0.0000e+00, 0.0000e+00, 0.0000e+00])

In [21]:
torch.mul(loss_new, 10)

tensor([0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        1.4400e+02, 1.0000e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00])

In [49]:
x1 = x.numpy()
y1 = y.numpy()

loss = np.zeros(x1.shape)
for i in range(x1.shape[0]):
    if (x1[i] <=0 and y1[i]==0) or (x1[i] > 0.42 and y1[i] >0.42):
        loss[i] = 0
    else:
        loss[i] = (x1[i] - y1[i])**2

loss



array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.25      , 0.09000001, 0.01      , 0.        , 0.        ,
       0.        ])

In [38]:
loss

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])