In [4]:
import numpy as np
import matplotlib.pyplot as plt
import torch 

/home/xiao/miniconda3/envs/mujoco_sim/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [68]:
B = np.array([[5,3, 0], [0,10, 1]])
B = torch.Tensor(B)
B

tensor([[ 5.,  3.,  0.],
        [ 0., 10.,  1.]])

In [69]:
A = B.repeat(5, 1)
A

tensor([[ 5.,  3.,  0.],
        [ 0., 10.,  1.],
        [ 5.,  3.,  0.],
        [ 0., 10.,  1.],
        [ 5.,  3.,  0.],
        [ 0., 10.,  1.],
        [ 5.,  3.,  0.],
        [ 0., 10.,  1.],
        [ 5.,  3.,  0.],
        [ 0., 10.,  1.]])

In [70]:
A.reshape(5,2,3)

tensor([[[ 5.,  3.,  0.],
         [ 0., 10.,  1.]],

        [[ 5.,  3.,  0.],
         [ 0., 10.,  1.]],

        [[ 5.,  3.,  0.],
         [ 0., 10.,  1.]],

        [[ 5.,  3.,  0.],
         [ 0., 10.,  1.]],

        [[ 5.,  3.,  0.],
         [ 0., 10.,  1.]]])

In [41]:

AA  = torch.Tensor([[[ 5.,  3.,  0.],
         [ 0., 10.,  1.]],

        [[ 6.,  3.,  0.],
         [ 7., 10.,  1.]],

        [[ 8.,  3.,  0.],
         [ 9., 10.,  1.]],

        [[ 10.,  3.,  0.],
         [ 11., 10.,  1.]],

        [[ 12.,  3.,  0.],
         [ 13., 10.,  1.]]])
AA

tensor([[[ 5.,  3.,  0.],
         [ 0., 10.,  1.]],

        [[ 6.,  3.,  0.],
         [ 7., 10.,  1.]],

        [[ 8.,  3.,  0.],
         [ 9., 10.,  1.]],

        [[10.,  3.,  0.],
         [11., 10.,  1.]],

        [[12.,  3.,  0.],
         [13., 10.,  1.]]])

In [42]:
AA[0,:,:]

tensor([[ 5.,  3.,  0.],
        [ 0., 10.,  1.]])

In [65]:
ax_0 = np.arange(AA.shape[0])[:,None]
ax_2 = np.arange(AA.shape[2])[None,:]
ax_0

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [72]:
a = np.array([1,0,2,3,4])
a.reshape(-1,1)

array([[1],
       [0],
       [2],
       [3],
       [4]])

In [71]:
AA[ax_0, np.array([[0],[0],[1],[1],[1]]), ax_2]

tensor([[ 5.,  3.,  0.],
        [ 6.,  3.,  0.],
        [ 9., 10.,  1.],
        [11., 10.,  1.],
        [13., 10.,  1.]])

In [47]:
arr_3d = np.arange(2*3*4).reshape(2,3,4)
arr_2d = np.array(([3,2,0], [2,3,2]))

ax_0 = np.arange(arr_3d.shape[0])[:,None]
ax_1 = np.arange(arr_3d.shape[1])[None,:]

arr_3d[ax_0, ax_1, arr_2d]

array([[ 3,  6,  8],
       [14, 19, 22]])

In [52]:
ax_0

array([[0],
       [1]])

In [53]:
ax_1

array([[0, 1, 2]])

In [48]:
arr_3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [77]:
a = np.array([[1,2], [1,3], [1,4]])
min_index = np.array([1,0,1]).reshape(-1,1)
min_index

array([[1],
       [0],
       [1]])

In [82]:
b = a[[[0],[1],[2]], min_index]
b

array([[2],
       [1],
       [4]])

In [84]:
b.flatten()

array([2, 1, 4])

In [4]:
A = np.array([[5,3], [1,2]])
np.linalg.inv(A)

array([[ 0.28571429, -0.42857143],
       [-0.14285714,  0.71428571]])

In [8]:
M = A @ B @ np.linalg.inv(A)
np.linalg.eig(M)

(array([5., 1.]),
 array([[0.98058068, 0.83205029],
        [0.19611614, 0.5547002 ]]))

In [9]:
5/np.sqrt(26)

0.9805806756909202